// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimulationContextLib;

#nullable disable

namespace SimulationContextLib.Migrations
{
    [DbContext(typeof(SimulationContext))]
    [Migration("20251109135416_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimulationContextLib.ForkUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ForkId")
                        .HasColumnType("integer");

                    b.Property<string>("ForkOwner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("UpdateTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("ForkUpdates");
                });

            modelBuilder.Entity("SimulationContextLib.PhilosopherUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("UpdateTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("PhilosopherUpdates");
                });
#pragma warning restore 612, 618
        }
    }
}
