<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ForkLib/ForkLib.csproj" />
    <ProjectReference Include="../PhilosopherLib/PhilosopherLib.csproj" />
    <ProjectReference Include="../SimulationContextLib/SimulationContextLib.csproj" />
    <ProjectReference Include="../SimulationSettingsLib/SimulationSettingsLib.csproj" />
    <ProjectReference Include="../StatisticsLib/StatisticsLib.csproj" />
    <ProjectReference Include="../StrategyContractLib/StrategyContractLib.csproj" />
    <ProjectReference Include="../StrategyImplementationLib/StrategyImplementationLib.csproj" />
    <ProjectReference Include="../WebPhilosopher/WebPhilosopher.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.10" />
  </ItemGroup>

</Project>
